# Form implementation generated from reading ui file 'grade_calculator.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QMainWindow, QMessageBox, QDialog, QWidget,
                             QPushButton, QHBoxLayout, QTableWidgetItem,
                             QFormLayout, QLineEdit, QComboBox, QDialogButtonBox)
from logic import GradeCalculator, Course, Assignment


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1283, 794)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 921, 80))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.studentGradeCalc = QtWidgets.QLabel(parent=self.frame)
        self.studentGradeCalc.setGeometry(QtCore.QRect(10, 0, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.studentGradeCalc.setFont(font)
        self.studentGradeCalc.setObjectName("studentGradeCalc")
        self.overallGPA = QtWidgets.QLabel(parent=self.frame)
        self.overallGPA.setGeometry(QtCore.QRect(770, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.overallGPA.setFont(font)
        self.overallGPA.setObjectName("overallGPA")
        self.courseNameLabel = QtWidgets.QLabel(parent=self.frame)
        self.courseNameLabel.setGeometry(QtCore.QRect(10, 40, 171, 31))
        self.courseNameLabel.setObjectName("courseNameLabel")
        self.overallGPALabel = QtWidgets.QLabel(parent=self.frame)
        self.overallGPALabel.setGeometry(QtCore.QRect(770, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.overallGPALabel.setFont(font)
        self.overallGPALabel.setObjectName("overallGPALabel")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 120, 521))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.myCourses = QtWidgets.QLabel(parent=self.frame_2)
        self.myCourses.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.myCourses.setObjectName("myCourses")
        self.addCourseBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.addCourseBtn.setGeometry(QtCore.QRect(70, 10, 31, 17))
        self.addCourseBtn.setObjectName("addCourseBtn")
        self.courseList = QtWidgets.QListWidget(parent=self.frame_2)
        self.courseList.setGeometry(QtCore.QRect(0, 40, 121, 401))
        self.courseList.setObjectName("courseList")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(150, 110, 781, 80))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(10, 30, 111, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(140, 0, 120, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_6.setObjectName("frame_6")
        self.currentGrade = QtWidgets.QLabel(parent=self.frame_5)
        self.currentGrade.setGeometry(QtCore.QRect(0, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.currentGrade.setFont(font)
        self.currentGrade.setObjectName("currentGrade")
        self.currentGradeLabel = QtWidgets.QLabel(parent=self.frame_5)
        self.currentGradeLabel.setGeometry(QtCore.QRect(80, 10, 31, 16))
        self.currentGradeLabel.setObjectName("currentGradeLabel")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(130, 30, 111, 41))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(140, 0, 120, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_8.setObjectName("frame_8")
        self.percentage = QtWidgets.QLabel(parent=self.frame_7)
        self.percentage.setGeometry(QtCore.QRect(0, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.percentage.setFont(font)
        self.percentage.setWordWrap(False)
        self.percentage.setObjectName("percentage")
        self.percentageLabel = QtWidgets.QLabel(parent=self.frame_7)
        self.percentageLabel.setGeometry(QtCore.QRect(70, 10, 51, 16))
        self.percentageLabel.setObjectName("percentageLabel")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(250, 30, 120, 41))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_9.setObjectName("frame_9")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(140, 0, 120, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_10.setObjectName("frame_10")
        self.points = QtWidgets.QLabel(parent=self.frame_9)
        self.points.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.points.setObjectName("points")
        self.pointsLabel = QtWidgets.QLabel(parent=self.frame_9)
        self.pointsLabel.setGeometry(QtCore.QRect(70, 10, 41, 16))
        self.pointsLabel.setObjectName("pointsLabel")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_11.setGeometry(QtCore.QRect(380, 30, 120, 41))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(140, 0, 120, 80))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_12.setObjectName("frame_12")
        self.gpaPoints = QtWidgets.QLabel(parent=self.frame_11)
        self.gpaPoints.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.gpaPoints.setObjectName("gpaPoints")
        self.gpaPointsLabel = QtWidgets.QLabel(parent=self.frame_11)
        self.gpaPointsLabel.setGeometry(QtCore.QRect(70, 10, 41, 16))
        self.gpaPointsLabel.setObjectName("gpaPointsLabel")
        self.addAssignmentBtn = QtWidgets.QPushButton(parent=self.frame_3)
        self.addAssignmentBtn.setGeometry(QtCore.QRect(510, 0, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.addAssignmentBtn.setFont(font)
        self.addAssignmentBtn.setStyleSheet("")
        self.addAssignmentBtn.setObjectName("addAssignmentBtn")
        self.deleteCourseBtn = QtWidgets.QPushButton(parent=self.frame_3)
        self.deleteCourseBtn.setGeometry(QtCore.QRect(660, 0, 121, 71))
        self.deleteCourseBtn.setObjectName("deleteCourseBtn")
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(150, 220, 781, 391))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.assignmentTable = QtWidgets.QTableWidget(parent=self.frame_4)
        self.assignmentTable.setGeometry(QtCore.QRect(0, 0, 781, 321))
        self.assignmentTable.setSizeIncrement(QtCore.QSize(6, 0))
        self.assignmentTable.setObjectName("assignmentTable")
        self.assignmentTable.setColumnCount(4)
        self.assignmentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.assignmentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignmentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignmentTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignmentTable.setHorizontalHeaderItem(3, item)
        self.assignmentTable.horizontalHeader().setDefaultSectionSize(180)
        self.assignmentTable.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.studentGradeCalc.setText(_translate("MainWindow", "Student Grade Calculator"))
        self.overallGPA.setText(_translate("MainWindow", "Overall GPA"))
        self.courseNameLabel.setText(_translate("MainWindow", "Select a Course"))
        self.overallGPALabel.setText(_translate("MainWindow", "_"))
        self.myCourses.setText(_translate("MainWindow", "My Courses"))
        self.addCourseBtn.setText(_translate("MainWindow", "+"))
        self.currentGrade.setText(_translate("MainWindow", "Current Grade"))
        self.currentGradeLabel.setText(_translate("MainWindow", "__"))
        self.percentage.setText(_translate("MainWindow", "Percentage"))
        self.percentageLabel.setText(_translate("MainWindow", "__"))
        self.points.setText(_translate("MainWindow", "Points"))
        self.pointsLabel.setText(_translate("MainWindow", "__/__"))
        self.gpaPoints.setText(_translate("MainWindow", "GPA"))
        self.gpaPointsLabel.setText(_translate("MainWindow", "__"))
        self.addAssignmentBtn.setText(_translate("MainWindow", "Add Assignment"))
        self.deleteCourseBtn.setText(_translate("MainWindow", "Delete Course"))
        item = self.assignmentTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Assignment Name"))
        item = self.assignmentTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Score"))
        item = self.assignmentTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Grade"))
        item = self.assignmentTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actions"))

# NON AUTOMATED CODE BELOW

'''
SOURCES: https://www.youtube.com/watch?v=Z1N9JzNax2k
https://www.youtube.com/watch?v=GkgMTyiLtWk
'''

class GradeCalculatorGUI(QMainWindow):
    """Main window GUI for the grade calculator."""

    def __init__(self) -> None:
        """Initialize the main window."""
        super().__init__()

        # Setup UI
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Initialize controller
        self.controller = GradeCalculator()
        self.current_course: Course = None

        # Connect buttons
        self.ui.addCourseBtn.clicked.connect(self.add_course)
        self.ui.deleteCourseBtn.clicked.connect(self.delete_course)
        self.ui.addAssignmentBtn.clicked.connect(self.add_assignment)
        self.ui.courseList.currentRowChanged.connect(self.on_course_selected)

        # Initialize display
        self.refresh_course_list()
        self.update_grade_display()

    def refresh_course_list(self) -> None:
        """Refresh the course list display."""
        self.ui.courseList.clear()
        for course in self.controller.get_all_courses():
            letter_grade = course.get_letter_grade()
            self.ui.courseList.addItem(f"{course.name} - {letter_grade}")

    def on_course_selected(self, index: int) -> None:
        """Toggle through course selection."""
        # CHATGPT generated
        courses = self.controller.get_all_courses()

        if index >= 0 and index < len(courses):
            self.current_course = courses[index]
            self.ui.courseNameLabel.setText(self.current_course.name)
            self.load_assignments()
            self.update_grade_display()
        else:
            self.current_course = None
            self.ui.courseNameLabel.setText("Select a course")
            self.ui.assignmentTable.setRowCount(0)
            self.update_grade_display()

    def load_assignments(self) -> None:
        """Load assignments into the table."""
        # TurtleCode - https://www.youtube.com/watch?v=zfLc45RQ9Zk
        if not self.current_course:
            self.ui.assignmentTable.setRowCount(0)
            return

        self.ui.assignmentTable.setRowCount(0)

        for assignment in self.current_course.assignments:
            row = self.ui.assignmentTable.rowCount()
            self.ui.assignmentTable.insertRow(row)

            # Assignment name
            self.ui.assignmentTable.setItem(row, 0, QTableWidgetItem(assignment.name))

            # Score
            self.ui.assignmentTable.setItem(row, 1, QTableWidgetItem(f"{assignment.score}/{assignment.max_points}"))

            # Percentage
            self.ui.assignmentTable.setItem(row, 2, QTableWidgetItem(f"{assignment.get_percentage():.1f}%"))

            # Delete button
            delete_btn = QPushButton("Delete")
            delete_btn.clicked.connect(lambda checked, a=assignment: self.delete_assignment(a))
            self.ui.assignmentTable.setCellWidget(row, 3, delete_btn)

    def update_grade_display(self) -> None:
        """Update all grade-related labels (course + overall)."""

        # Always update overall GPA (even if no course is selected)
        overall_gpa = self.controller.calculate_overall_gpa()
        self.ui.overallGPALabel.setText(f"{overall_gpa:.2f}")

        if not self.current_course:
            self.ui.currentGradeLabel.setText("—")
            self.ui.percentageLabel.setText("—")
            self.ui.pointsLabel.setText("—")
            self.ui.gpaPointsLabel.setText("—")
            return

        # Course numbers
        percentage = self.current_course.calculate_grade()
        letter_grade = self.current_course.get_letter_grade()
        course_gpa = self.current_course.calculate_gpa()

        # Points totals
        total_earned = 0.0
        total_possible = 0.0
        for a in self.current_course.assignments:
            total_earned += a.score
            total_possible += a.max_points

        self.ui.currentGradeLabel.setText(letter_grade)
        self.ui.percentageLabel.setText(f"{percentage:.1f}%")
        self.ui.pointsLabel.setText(f"{total_earned:.0f}/{total_possible:.0f}")
        self.ui.gpaPointsLabel.setText(f"{course_gpa:.2f}")

    def add_course(self) -> None:
        """Add a new course."""
        dialog = CourseDialog(self)
        if dialog.exec():
            try:
                name = dialog.get_name()
                self.controller.add_course(name)
                self.refresh_course_list()
            except ValueError as e:
                QMessageBox.warning(self, "Error", str(e))


    def delete_course(self) -> None:
        """Delete the current course."""
        if not self.current_course:
            QMessageBox.warning(self, "No Course", "Please select a course to delete.")
            return

        reply = QMessageBox.question(
            self,
            "Confirm Delete",
            f"Delete {self.current_course.name}?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )

        if reply == QMessageBox.StandardButton.Yes:
            self.controller.delete_course(self.current_course)
            self.current_course = None
            self.refresh_course_list()

    def add_assignment(self) -> None:
        """Add a new assignment."""
        if not self.current_course:
            QMessageBox.warning(self, "No Course", "Please select a course first.")
            return

        dialog = AssignmentDialog(self)
        if dialog.exec():
            try:
                data = dialog.get_data()
                self.controller.add_assignment(
                    self.current_course,
                    data['name'],
                    data['score'],
                    data['max_points']
                )
                self.load_assignments()
                self.update_grade_display()
                self.refresh_course_list()
            except ValueError as e:
                QMessageBox.warning(self, "Error", str(e))

    def delete_assignment(self, assignment: Assignment) -> None:
        """Delete an assignment."""
        reply = QMessageBox.question(
            self,
            "Confirm Delete",
            f"Delete {assignment.name}?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )

        if reply == QMessageBox.StandardButton.Yes:
            self.controller.delete_assignment(self.current_course, assignment)
            self.load_assignments()
            self.update_grade_display()
            self.refresh_course_list()


class CourseDialog(QDialog):
    """Dialog for adding a course."""

    def __init__(self, parent: QWidget = None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Add Course")

        layout = QFormLayout(self)
        self.nameInput = QLineEdit()
        layout.addRow("Course Name:", self.nameInput)

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel
        )
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addRow(buttons)

    def get_name(self) -> str:
        """Get the entered course name."""
        return self.nameInput.text().strip()


class AssignmentDialog(QDialog):
    """Dialog for adding an assignment."""

    def __init__(self, parent: QWidget = None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Add Assignment")

        layout = QFormLayout(self)

        self.nameInput = QLineEdit()
        self.scoreInput = QLineEdit()
        self.maxPointsInput = QLineEdit()

        layout.addRow("Assignment Name:", self.nameInput)
        layout.addRow("Score:", self.scoreInput)
        layout.addRow("Max Points:", self.maxPointsInput)

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel
        )
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addRow(buttons)

    def get_data(self) -> dict:
    name = self.nameInput.text().strip()
    score_text = self.scoreInput.text().strip()
    max_points_text = self.maxPointsInput.text().strip()

    if not name:
        raise ValueError("Assignment name cannot be empty.")

    if not score_text or not max_points_text:
        raise ValueError("Please enter both a score and max points.")

    try:
        score = float(score_text)
        max_points = float(max_points_text)
    except ValueError:
        raise ValueError("Score and max points must be valid numbers.")

    return {
        'name': name,
        'score': score,
        'max_points': max_points
    }

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
